### ISSUE TITLE
can this work in compilation mode?

### ISSUE THREAD

**Issue by blaenk** [atomontage/xterm-color#3]
Does it even make sense to? Not sure, but I found this after looking into enabling ANSI colors in compilation mode (see [this](http://stackoverflow.com/questions/13397737/ansi-coloring-in-compilation-mode)).

**Comment by atomontage** [comment]
I don't see why not, I'll have a look this weekend.

You could also try doing it yourself and making a pull request,
shouldn't be hard.

Chris

**Comment by blaenk** [comment]
Eh, I just figured I would ask, I'm not demanding or dying for this, I was just wondering if it would even make sense. I'm not too familiar with the technical details of this nor how I would get it working, though I did give it a shot based on the link I mentioned, but that thread seems to do things differently.

**Comment by atomontage** [comment]
No worries.

If they got ansi-color to work, then I can probably get mine
to work with minimal effort too.

I'll have a look at it first chance I get.

**Comment by blaenk** [comment]
Sounds great! No rush on my part though!

**Comment by atomontage** [comment]
I added support for standalone compilation-mode buffers. Look at the updated
documentation for the configuration.

For comint-mode buffers that use compilation-shell-minor-mode, the comint configuration
in the documentation works fine.

The ansi-color config at the URL you posted (and also here: http://endlessparentheses.com/ansi-colors-in-the-compilation-buffer-output.html) is not optimal, since it can processes the incoming bytes in discrete batches via regular expressions, which may lead to corrupted output and other inaccuracies.
