### ISSUE TITLE
Upstreaming?

### ISSUE THREAD

**Issue by cpitclaudel** [atomontage/xterm-color#30]
Hi there,

If I understand correctly, this script entirely superseeds ansi-color, except for already propertized strings; is that correct?

If so, could this be merged into the upstream ansi-color, so that things work out of the box for Emacs users instead of having to install an extra package?

Thanks for your hard work!

**Comment by atomontage** [comment]
Hi Clément,

xterm-color.el is not a full replacement for ansi-color, since the
underlying model is fundamentally different. Ansi-color keeps minimal
state (the only buffer-local variable is ansi-color-context which is
optional) and simply uses regular expressions to detect and map SGR
attributes to Emacs faces. It also supports overlays and being applied
to a region (with ansi-color-apply-on-region). For those reasons,
even if xterm-color.el was upstreamed and became the default, I'd keep
ansi-color.el around.

xterm-color.el tries to properly emulate the entire SGR state machine,
which implies per-character processing and keeping significant buffer-local
state. This means that it's "correct" as per specification and can support
far more escape sequences and sequence-combinations than ansi-color.el but
it also means that it's not a drop-in replacement and requires more
configuration (which is documented). It's also more complicated
implementation-wise but not significantly more lines of code (871 vs 648).
I do think though that the code is well-commented and structured.

I'd like to see it upstreamed but I don't really have a lot of time
to devote for that. I've also not signed any copyright assignment
papers. If all that's required of me is the latter, I'll gladly do it,
but I can't expend more energy than that at the moment.

**Comment by cpitclaudel** [comment]
Thanks for clarifying (and for the awesome work!)! 

Signing copyright papers is quite easy (what's more painful usually for projects with a lot of history is chasing all past contributors to get them to sign too).   But I think there would be a bit more work involved to upstream (off the top of my head, I think it would require texinfo documentation, a default Emacs configuration that uses xterm-color for anything that ansi-color isn't required for anymore, and likely even some extensions to be able to deprecate ansi-color).

So let's shelve the idea for now :) Thanks again for your work!
