### ISSUE TITLE
Standalone compilation-mode buffer support

### ISSUE THREAD

**Issue by seagle0128** [atomontage/xterm-color#31]
Thanks for the great package! It's easy to handle ANSI control sequence and better than `ansi-color`.

Regarding the standalone compilation-mode buffer support, I notice using `compilation-start-hook` in README. I am curious why `compilation-filter-hook` is not used here. I am using `compilation-filter-hook` instead of it and it seems working well. The snippet is below.

```elisp
(add-hook 'compilation-filter-hook
            (lambda ()
              (with-silent-modifications
                (insert (xterm-color-filter
                         (delete-and-extract-region compilation-filter-start
                                                    (point-max)))))))
```

**Comment by atomontage** [comment]
Well as you demonstrate, the problem with compilation-filter-hook is that the output is first placed in the buffer and then the hook is executed. Your anonymous function ends up calling delete-and-extract-region. This is ugly in my view. I would rather process the string before it even hits the buffer. That way, there can be other functions in compilation-filter-hook that do whatever processing they want, without the issues that would arise if they were executed before your anonymous function and messed with ANSI state machine characters.

One better solution and the one I use in my own config is:

```emacs-lisp
(defun my/advice-compilation-filter (f proc string)
  (funcall f proc (xterm-color-filter string)))

(advice-add 'compilation-filter :around #'my/advice-compilation-filter)
```
Your question reminded me to update the documentation and mention this but also
mention that compilation-shell-minor-mode is no longer supported if the example config I 
illustrate is chosen, since I’m disabling font-locking and compilation-shell-minor-mode
needs it. The performance boost is far too great for me to care about losing the latter,
but I think I’ll document both cases and let users decide.

**Comment by seagle0128** [comment]
I am thinking perhaps it's better provide this function to make the codes more elegant.

```elisp
(defun xterm-color-compilation-filter ()
    (with-silent-modifications
       (insert (xterm-color-filter
               (delete-and-extract-region compilation-filter-start
                                          (point-max)))))))

;; This is more elegant, and same as the advisor you mentioned
(add-hook 'compilation-filter-hook #'xterm-color-compilation-filter)
```

**Comment by atomontage** [comment]
Closing this as I've updated the documentation.

It's not a good idea for me to include xterm-color-compilation-filter as there is a number of different ways someone may want to implement this. My recommended way is included in the example configuration I provide in the documentation.
